import numpy as np
import matplotlib.pylab as plt
datos=np.genfromtxt("datos_omega.dat", skip_header=1)
datoslp1=np.genfromtxt("datoslp1.dat")
datoslp2=np.genfromtxt("datoslp2.dat")
datoslp3=np.genfromtxt("datoslp3.dat")
datoslp4=np.genfromtxt("datoslp4.dat")
daticos=np.genfromtxt("datoslp.dat")
masas=np.genfromtxt("masa.dat")
masas1=np.genfromtxt("masa1.dat")
masas2=np.genfromtxt("masa2.dat")
gammas=np.genfromtxt("gamma.dat")
gammas1=np.genfromtxt("gamma2.dat")
gammas2=np.genfromtxt("gamma3.dat")
plt.figure(figsize=[15,15])
plt.subplot(3,1,1)
plt.plot(datos[:,3],datos[:,0], c='pink')
plt.title("Maximas amplitudes para diferentes omegas piso 1")
plt.xlabel("omega")
plt.ylabel("posicion(m)")
plt.subplot(3,1,2)
plt.plot(datos[:,3],datos[:,1], c='cyan', label="U2")
plt.title("Maximas amplitudes para diferentes omegas piso 2")
plt.xlabel("omega")
plt.ylabel("posicion(m)")
plt.subplot(3,1,3)
plt.plot(datos[:,3],datos[:,2], c='orange', label="U3")
plt.title("Maximas amplitudes para diferentes omegas piso 3")
plt.xlabel("omega")
plt.ylabel("posicion(m)")
plt.savefig("plot_omegas.pdf")
plt.figure(figsize=[10,10])
plt.plot(daticos[:,3],daticos[:,0], c='pink', label="U1")
plt.plot(daticos[:,3],daticos[:,1], c='cyan', label="U2")
plt.plot(daticos[:,3],daticos[:,2], c='orange', label="U3")
plt.legend()
plt.title("Desplazamiento para omega=1*raiz(k/m)")
plt.xlabel("tiempo(s)")
plt.ylabel("posicion(m)")
plt.savefig("plot_omegafijo.pdf")
x=datos[:,0]
y=datos[:,1]
z=datos[:,2]
c=datos[:,3]
pos_maxima=np.argmax(x)
omega1=(c[pos_maxima])
pos_minima=np.argmin(x)
omega2=(c[pos_minima])
pos_maxima1=np.argmax(y)
omega3=(c[pos_maxima1])
pos_minima1=np.argmin(z)
omega4=(c[pos_minima1])

plt.figure(figsize=[10,10])
plt.plot(datoslp1[:,3],datoslp1[:,0], c='pink', label="U1")
plt.plot(datoslp1[:,3],datoslp1[:,1], c='cyan', label="U2")
plt.plot(datoslp1[:,3],datoslp1[:,2], c='orange', label="U3")
plt.legend()
plt.title("Desplazamiento para omega= 3.72267")
plt.xlabel("tiempo(s)")
plt.ylabel("posicion(m)")
plt.savefig("plot_omega1.pdf")
plt.figure(figsize=[10,10])
plt.plot(datoslp2[:,3],datoslp2[:,0], c='pink', label="U1")
plt.plot(datoslp2[:,3],datoslp2[:,1], c='cyan', label="U2")
plt.plot(datoslp2[:,3],datoslp2[:,2], c='orange', label="U3")
plt.legend()
plt.title("Desplazamiento para omega=0.402837")
plt.xlabel("tiempo(s)")
plt.ylabel("posicion(m)")
plt.savefig("plot_omega2.pdf")
plt.figure(figsize=[10,10])
plt.plot(datoslp4[:,3],datoslp4[:,0], c='pink', label="U1")
plt.plot(datoslp4[:,3],datoslp4[:,1], c='cyan', label="U2")
plt.plot(datoslp4[:,3],datoslp4[:,2], c='orange', label="U3")
plt.legend()
plt.title("Desplazamiento para omega=3.92266")
plt.xlabel("tiempo(s)")
plt.ylabel("posicion(m)")
plt.savefig("plot_omega4.pdf")
plt.figure(figsize=[10,10])
plt.plot(datoslp3[:,3],datoslp3[:,0], c='pink', label="U1")
plt.plot(datoslp3[:,3],datoslp3[:,1], c='cyan', label="U2")
plt.plot(datoslp3[:,3],datoslp3[:,2], c='orange', label="U3")
plt.legend()
plt.title("Desplazamiento para omega=2.32274")
plt.xlabel("tiempo(s)")
plt.ylabel("posicion(m)")
plt.savefig("plot_omega3.pdf")
plt.figure(figsize=[10,10])
plt.plot(masas[:,3],masas[:,0], c='pink', label="U1")
plt.plot(masas[:,3],masas[:,1], c='cyan', label="U2")
plt.plot(masas[:,3],masas[:,2], c='orange', label="U3")
plt.legend()
plt.title("Desplazamiento para omega= 1*sqrt(k/m) y masa de 5 Toneladas")
plt.xlabel("tiempo(s)")
plt.ylabel("posicion(m)")
plt.savefig("masas.pdf")
plt.figure(figsize=[10,10])
plt.plot(masas1[:,3],masas1[:,0], c='pink', label="U1")
plt.plot(masas1[:,3],masas1[:,1], c='cyan', label="U2")
plt.plot(masas1[:,3],masas1[:,2], c='orange', label="U3")
plt.legend()
plt.title("Desplazamiento para omega=1*sqrt(k/m) y masa de media tonelada")
plt.xlabel("tiempo(s)")
plt.ylabel("posicion(m)")
plt.savefig("masas1.pdf")
plt.figure(figsize=[10,10])
plt.plot(masas2[:,3],masas2[:,0], c='pink', label="U1")
plt.plot(masas2[:,3],masas2[:,1], c='cyan', label="U2")
plt.plot(masas2[:,3],masas2[:,2], c='orange', label="U3")
plt.legend()
plt.title("Desplazamiento para omega=1*sqrt(k/m) y masas de dos tonelada")
plt.xlabel("tiempo(s)")
plt.ylabel("posicion(m)")
plt.savefig("masas2.pdf")
plt.figure(figsize=[10,10])
plt.plot(gammas[:,3],gammas[:,0], c='pink', label="U1")
plt.plot(gammas[:,3],gammas[:,1], c='cyan', label="U2")
plt.plot(gammas[:,3],gammas[:,2], c='orange', label="U3")
plt.legend()
plt.title("Desplazamiento para omega= 0.402837 y gamma diferentes de0")
plt.xlabel("tiempo(s)")
plt.ylabel("posicion(m)")
plt.savefig("gammas.pdf")
plt.figure(figsize=[10,10])
plt.plot(gammas1[:,3],gammas1[:,0], c='pink', label="U1 y gamma=0.7")
plt.plot(gammas1[:,3],gammas1[:,1], c='cyan', label="U2 y gamma=0.4")
plt.plot(gammas1[:,3],gammas1[:,2], c='orange', label="U3 y gamma=0.4")
plt.legend()
plt.title("Desplazamiento para omega= 0.402837 y gamma superior piso")
plt.xlabel("tiempo(s)")
plt.ylabel("posicion(m)")
plt.savefig("gammas1.pdf")
plt.figure(figsize=[10,10])
plt.plot(gammas2[:,3],gammas2[:,0], c='pink', label="U1 y gamma=0.4")
plt.plot(gammas2[:,3],gammas2[:,1], c='cyan', label="U2 y gamma=0.7")
plt.plot(gammas2[:,3],gammas2[:,2], c='orange', label="U3 y gamma=0.7")
plt.legend()
plt.title("Desplazamiento para omega= 0.402837 y gamma superior segundo y tercer piso")
plt.xlabel("tiempo(s)")
plt.ylabel("posicion(m)")
plt.savefig("gammas2.pdf")
plt.figure(figsize=[10,10])
plt.plot(gammas2[:,3],gammas2[:,0], c='pink', label="U1 y gamma=0.4")
plt.plot(gammas2[:,3],gammas2[:,1], c='cyan', label="U2 y gamma=0.7")
plt.plot(gammas2[:,3],gammas2[:,2], c='orange', label="U3 y gamma=0.7")
plt.legend()
plt.title("Desplazamiento para omega= 0.402837 y gamma superior segundo y tercer piso")
plt.xlabel("tiempo(s)")
plt.ylabel("posicion(m)")
plt.savefig("gammas2.pdf")